### ISSUE TITLE
Lighting feedback

### ISSUE THREAD

**Issue by Azmoria** [cyruzzo/AboveVTT#899]
Starting this to keep track of feedback with regards to dynamic lighting. Feel free to add to this in the comments below.

In progress:

---

Maybes:

- [x] Feature Request Discord - A way to default monster light off. We currently have a toggle on scenes to completely disable the light feature but it's been requested that a default token option still be made available. This is due to their computer not being able to run more than a few light sources without bogging down. They'd still like to use light but would like not to have to disable it manually on each monster in the customizations. Edit: We've seen some no longer experiencing performance issues since 0.90 🥳
---

Finished 

- [x] Feature Request Discord - Wall heights - set bottom/top of walls elevation default to -infinity and +infinity. 

- [x] Feature Request Discord - Now that bucket fill has performance improved and a radius can be set, an inner and outer radius to allow for bright/dim. If a color is partially transparent the same color can be used or slightly modified to be partially transparent for the outer radius if not.
- [x] Feature Request Discord - Invisible/see through walls/doors for windows.
- [x] A way to disable DM's always getting vision of tokens when selected. Prehaps make this an option or move the see vision to a hotkey. Testing out another solution in  PR #912 - awaiting feedback

- [x] A way to draw light - This actually feels pretty good and I think would be less intensive - example in this thread https://discord.com/channels/815028457851191326/1102299459452411985
- [x] QoL - Allow tokens who are mostly visible to be visible even if their center pixel is in darkness. Perhaps raise raycasting above tokens. (pointer-events: none on raycasting) https://github.com/cyruzzo/AboveVTT/pull/1034
- [x] Make vision/light available in token customizations PR #943
- [x] - Monsters and player tokens work slightly differently atm. This is due to the `player accessible stats` not being an option on players. Therefore we reveal other players light even when not in LoS when `reveal light to players` is enabled on a player token. This is to allow for games with fewer players that use multiple PCs, streaming all PC's view or just preference. We may consider taking player accessibly stats light reveal away and moving it to an option under light for revealing light when out of line of sight. Or another option in the future depending where we feel options need to land and what we have space for. The current work around is to instead use a 'torch' token that has reveal light to players enabled that you can attached to a player if you don't want your players always seeing others light. I'm currently thinking a drop down option with the current reveal light and always show light options. I think this is resolved in PR #925
- [x] Option for drawing doors - convert to door eraser, erase a section of a wall replace it with a door? PR #901

- [x] Hidden tokens with reveal light on show a lower opacity in the DM view.  PR #903

- [x] Rectangle draw walls PR #901

- [x] Preset for 60ft and 120ft darkvision PR #905 

- [x] Currently to see other light sources at least 1 of the light aura ranges needs to be above 0.  I think seeing visible light sources should be available at 0/0 light ranges. PR #902 

- [x] Players with no token should only see player vision. PR #902 

- [x] The walls pick up the `select` draw style (dashed lines) when switching to the wall button. PR #901

- [x] Possibly limit vision range when not full darkness (and not full brightness)- to allow more variance in setup. ie. areas of the map already explored are visible in the fog but can't see tokens without vision. This somewhat works already if in a space that's enclosed enough that vision range isn't an issue. ~~This is ready to go in the `look` function, we just need to set the radius variable to the light aura range if we choose to do this.~~ This is probably a better way to do this less processing  PR #904
